### ISSUE TITLE
Sorry to disturb, but could you please update this overlay plugin to fit the latest version of Tesla and Atmosphere?

### ISSUE THREAD

**Issue by lbk2002** [minazuki19/MHGU-Monster-Info-Overlay#1]
I sincerely appreciate your work in creating this plugin. It's a wonderful plugin for me while playing MHGU, which really helps a lot to be sufficed to see the HP of monsters. Unfortunately, after I updated my Atmosphere and Tesla, launching this plugin will cause crash and the only thing I can do is to reboot my NS. The error code is 2001-0123, which means the plugin is outdated for this version of Tesla.  The latest version of Tesla is 1.0.6, and the version of Atmosphere is 1.5.1 . I even tried to learn how to make an overlay with the source code by myself, but It's too complex for me. So, could you please update this overlay plugin to fit the latest version of Tesla and Atmosphere? I would be very grateful to you for all your help! Wish you a good day.

**Comment by minazuki19** [comment]
Please try the latest version.

**Comment by lbk2002** [comment]
Thank you so much! Now this plugin is able to work, which really means a lot for me!
